version: '2'
services:
    hacksociety-app:
        image: hacksociety
        external_links:
            - hacksociety-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hacksociety?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hacksociety-mysql:
        extends:
            file: mysql.yml
            service: hacksociety-mysql
